tweak: removes local recording related code
optidatacloud/jitsi-meet pull request #2
Opened 2023-09-26 15:37 UTC by jeanchilger

Esta PR remove o código que executa de fato a gravação local no jitsi-meet. Apenas a parte que controla a interface (que nos interessa) foi mantida.

2023-09-26 16:34 UTC, Dovyski requested changes
Mais um fork nosso 😄 Eu fiz os comentários referentes a como eu gostaria de conduzir as alterações com o `jitsi-meet`. A ideia é remover o mínimo de código possível, construindo sempre através de classes novas (que herdam das existentes e sobrescrevem métodos).

2023-09-26 16:34 UTC, Dovyski commented on react/features/recording/components/Recording/LocalRecordingManager.web.ts
Essa alteração aqui me parece drástica de mais. Estamos apagando vários elementos que o próprio jitsi já implementou e teve que lidar com.

O caminho é aqui:

```ts
this.recorder = new MediaRecorder(this.stream, {
    mimeType: this.mediaType,
    videoBitsPerSecond: VIDEO_BIT_RATE
});
this.recorder.addEventListener('dataavailable', e => {
    if (e.data && e.data.size > 0) {
        this.recordingData.push(e.data);
        this.totalSize -= e.data.size;
        if (this.totalSize <= 0) {
            dispatch(stopLocalVideoRecording());
        }
    }
});
```

Criar uma abstração/config que defina qual é a classe que fará a gravação. Nossa implementação será pontual e voltada na criação de um `MediaRecorder`. Na maior parte do tempo, podemos fazer ele se comportar exatamente como o `MediaRecorder` do próprio jitsi. Vamos divergir quando tiver algo que é de nosso interesse.

Por exemplo,  na parte `this.recorder.addEventListener('dataavailable', e => {` provavelmente teremos que criar um método do próprio `LocalRecordingManager` que vai lidar com isso. Talvez repassar para o `mediaRecorder` fazer algo (que no nosso caso seria mandar a gravação para o back e zerar o buffer para começar uma gravação nova, sem despachar eventos).

2023-09-26 16:34 UTC, Dovyski commented on react/features/recording/components/Recording/web/RecordButton.ts
> -        ));
Ao invés de remover código, vamos usar a filosifia de ativsar ou desativar. Aqui daria para colocar uma propriedade no `RecordButton` que indica se ele abre ou não um modal quando há cliques nele. Dessa forma, não deixarmos o código existente "mutilado" e podemos contruir em cima da alteração.

2023-09-26 16:34 UTC, Dovyski commented on react/features/recording/components/Recording/web/RecordButton.ts
> +            : dispatch(startLocalVideoRecording(false));
Não usar operador ternário para fazer chamadas na mesma linha. Isso viola os princípios do clean code.

2023-09-26 16:59 UTC, jeanchilger commented
Obrigado pelos apontamentos :heart:. 

Concordo que para o longo prazo, o melhor é vandalizarmos o mínimo possível. Logo mais vou realizar as correções :shipit:.

2023-09-29 17:29 UTC, Dovyski approved these changes
Ficou ótimo! Obrigado palas alterações e empenho aqui! ❤️

2023-09-29 17:30 UTC, merged